services:
  # For command call use `docker exec mc_docker_soulkeeper rcon-cli <your_command>`
  mc_docker_soulkeeper:
    restart: no
    container_name: mc_docker_soulkeeper
    image: itzg/minecraft-server # https://github.com/itzg/docker-minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: true
      ONLINE_MODE: false
      # Forge --------------------
      TYPE: NEOFORGE
      VERSION: "1.21.1"
      NEOFORGE_VERSION: "21.1.216"
      # Paper --------------------
#      TYPE: PAPER
#      VERSION: 1.21.8
      # Custom -------------------
    #      CUSTOM_SERVER: https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/121/downloads/paper-1.21.1-121.jar
    volumes:
      - ./build/neoforge:/data # Forge
#      - ./build/bukkit:/data # Bukkit/Paper/Spigot
#      - ./build/velocity:/data # Velocity
#      - ./build/fabric:/data # Fabric